#!/usr/bin/env python3
"""Actively probe cluster services and select healthy Nginx backends.

This runs under supervisord on sys4. Ubuntu's open-source Nginx has no native
active upstream health checks, so this writes an Nginx map and gracefully
reloads Nginx only when a backend's health state changes.
"""

import json
import logging
import os
import subprocess
import time
import urllib.request
import urllib.error

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [CLUSTER-HEALTH %(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("cluster_health")

BACKENDS = {
    "sys1": {"url": "http://172.17.0.2:3000/health", "role": "frontend"},
    "sys2": {"url": "http://172.17.0.3:3000/health", "role": "primary-parsing,backup-ranking"},
    "sys3": {"url": "http://172.17.0.4:3000/health", "role": "primary-ranking,backup-parsing"},
    "sys4": {"url": "http://127.0.0.1:8000/health", "role": "gateway-orchestration"},
}

FAILURE_THRESHOLD = 3
RECOVERY_THRESHOLD = 2
CHECK_INTERVAL = 5.0
STATUS_FILE = "/tmp/cluster_health.json"
MAP_FILE = "/home/student/Jalasetu/runtime/jalasetu_upstream_maps.conf"


def probe(url: str, timeout: float = 3.0) -> tuple[bool, int, float, str]:
    start = time.time()
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "JalaSetu-HealthProber/1.0"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            latency_ms = round((time.time() - start) * 1000, 1)
            body = resp.read().decode("utf-8", errors="replace")
            return resp.status == 200, resp.status, latency_ms, body
    except urllib.error.HTTPError as e:
        latency_ms = round((time.time() - start) * 1000, 1)
        return False, e.code, latency_ms, str(e)
    except Exception as e:
        latency_ms = round((time.time() - start) * 1000, 1)
        return False, 0, latency_ms, str(e)


def nginx_map_text(state: dict[str, str]) -> str:
    # Unknown state keeps the configured route during the initial three-probe
    # grace period; only a thresholded failure removes a backend from routing.
    sys2_up = state.get("sys2") != "unhealthy"
    sys3_up = state.get("sys3") != "unhealthy"
    sys1_up = state.get("sys1") != "unhealthy"
    sys4_up = state.get("sys4") != "unhealthy"
    parsing = "sys2_parsing_primary" if sys2_up else (
        "sys2_parsing_fallback" if sys3_up else "jalasetu_unavailable"
    )
    terrain = "sys3_terrain_primary" if sys3_up else (
        "sys3_terrain_fallback" if sys2_up else "jalasetu_unavailable"
    )
    frontend = "sys1_frontend" if sys1_up else "jalasetu_unavailable"
    gateway = "sys4_gateway" if sys4_up else "jalasetu_unavailable"
    return (
        "# Generated by scripts/cluster_health_prober.py; do not edit.\n"
        f"map $host $sys2_parsing_target {{ default {parsing}; }}\n"
        f"map $host $sys3_terrain_target {{ default {terrain}; }}\n"
        f"map $host $sys1_frontend_target {{ default {frontend}; }}\n"
        f"map $host $sys4_gateway_target {{ default {gateway}; }}\n"
    )


def install_nginx_maps(state: dict[str, str]) -> None:
    """Atomically install maps, validate Nginx, and reload on state change."""
    desired = nginx_map_text(state)
    previous = None
    try:
        with open(MAP_FILE, "r", encoding="utf-8") as current_file:
            previous = current_file.read()
            if previous == desired:
                return
    except FileNotFoundError:
        pass

    os.makedirs(os.path.dirname(MAP_FILE), exist_ok=True)
    temp_path = MAP_FILE + ".tmp"
    with open(temp_path, "w", encoding="utf-8") as map_file:
        map_file.write(desired)
    os.replace(temp_path, MAP_FILE)
    check = subprocess.run(["sudo", "-n", "nginx", "-t"], capture_output=True, text=True)
    if check.returncode:
        logger.error("Nginx config validation failed after health-map update: %s", check.stderr.strip())
        if previous is not None:
            with open(temp_path, "w", encoding="utf-8") as map_file:
                map_file.write(previous)
            os.replace(temp_path, MAP_FILE)
        return
    reload_result = subprocess.run(
        ["sudo", "-n", "nginx", "-s", "reload"], capture_output=True, text=True
    )
    if reload_result.returncode:
        logger.error("Nginx reload failed after health-map update: %s", reload_result.stderr.strip())
        if previous is not None:
            with open(temp_path, "w", encoding="utf-8") as map_file:
                map_file.write(previous)
            os.replace(temp_path, MAP_FILE)
    else:
        logger.info("Nginx active backend map updated: %s", desired.splitlines()[1:])


def main():
    logger.info("Starting JalaSetu Active Cluster Health Prober...")
    failures = {name: 0 for name in BACKENDS}
    successes = {name: 0 for name in BACKENDS}
    state = {name: "unknown" for name in BACKENDS}

    while True:
        results = {}
        for name, info in BACKENDS.items():
            ok, code, latency_ms, body = probe(info["url"])
            if ok:
                if failures[name] > 0 or state[name] != "healthy":
                    logger.info(f"Backend {name} is HEALTHY (HTTP {code}, latency {latency_ms}ms)")
                failures[name] = 0
                successes[name] += 1
                if state[name] in ("unknown", "healthy") or successes[name] >= RECOVERY_THRESHOLD:
                    state[name] = "healthy"
            else:
                failures[name] += 1
                successes[name] = 0
                logger.warning(
                    f"Backend {name} health check FAILED ({failures[name]}/{FAILURE_THRESHOLD}) "
                    f"HTTP {code}, latency {latency_ms}ms: {body[:100]}"
                )
                if failures[name] >= FAILURE_THRESHOLD:
                    was_healthy = state[name] == "healthy"
                    state[name] = "unhealthy"
                    if was_healthy or failures[name] == FAILURE_THRESHOLD:
                        logger.error(
                            f"ALERT: Backend {name} is UNHEALTHY after {failures[name]} consecutive failures!"
                        )

            results[name] = {
                "status": state[name],
                "http_code": code,
                "latency_ms": latency_ms,
                "consecutive_failures": failures[name],
                "role": info["role"],
                "last_check": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            }

        try:
            install_nginx_maps(state)
            with open(STATUS_FILE + ".tmp", "w") as f:
                json.dump(
                    {
                        "cluster_status": "ok" if all(s == "healthy" for s in state.values()) else "degraded",
                        "nodes": results,
                        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    },
                    f,
                    indent=2,
                )
            os.replace(STATUS_FILE + ".tmp", STATUS_FILE)
        except Exception as e:
            logger.debug(f"Could not write status file: {e}")

        time.sleep(CHECK_INTERVAL)


if __name__ == "__main__":
    main()
